### ISSUE TITLE
Remote state not used for managed scopes and scopeMappings

### ISSUE THREAD

**Issue by Skg-754** [adorsys/keycloak-config-cli#1012]
### Current Behavior

When the environment variable IMPORT_REMOTESTATE_ENABLED=true is set, remote state is not working for "clientScopes" and "scopeMappings" resources. All "clientScopes" and "scopeMappings" which are not present in the json import files are deleted from keycloak. 

### Expected Behavior

When the environment variable IMPORT_REMOTESTATE_ENABLED=true, only "clientScopes" and "scopeMappings" present in the remote state and not present in the json import files should be deleted from keycloak.

### Steps To Reproduce

```markdown
1. Set env var IMPORT_REMOTESTATE_ENABLED=true
2. Create a ClientScope and a ScopeMapping manually in keycloak
3. Start a keycloak-config-cli with a JSON import file containing ClientScopes and ScopeMappings
4. Manually created ClientScope and ScopeMapping are deleted from keycloak.
```

### Environment

- Keycloak Version:  22.0.4
- keycloak-config-cli Version:  5.9.0 
- Java Version: 17.0.8

**Comment by Calebasah** [comment]
Hello @Skg-754 here is the current expected behavior

**Expected Behavior:**
When the environment variable `IMPORT_REMOTESTATE_ENABLED=true`, all resources, including "clientScopes" and "scopeMappings," that are present in the remote state should not be deleted. Instead, they should be updated with the data from the JSON import files. Only the resources that are not present in the remote state but are included in the JSON import files should be added to Keycloak.
