### ISSUE TITLE
Authentification flow migration

### ISSUE THREAD

**Issue by Adderin** [adorsys/keycloak-config-cli#1133]
### Problem Statement

We want to migrate to MFA and I successfully created PoC on dev env and now I want to export/apply everywhere. Can you help me with that? Is it applicable using your tool?

### Environment

- Keycloak Version: [e.g. 24.0.1]
- keycloak-config-cli Version: [e.g. 5.11.1]
- Java Version: [e.g. 21]

**Comment by Motouom** [comment]
Hello @Adderin,

Thank you for bringing your issue to our attention.

To adequately assess the feasibility of your use case scenario with KC-CLI, we require a comprehensive overview of your architecture. Please elaborate on your environments and specify how you intend to leverage the tool within your setup. This information will help us provide more targeted assistance.

Looking forward to your response.

**Comment by Adderin** [comment]
Hello @Motouom 
We currently have multiple environments: development, staging, and production. The goal is to replicate some configuration (MFA for instance) we successfully tested in the development environment across staging and production.

Now, what we do is a manual entry into each environment and our intention is to leverage KC-CLI to export the configuration (including authentication flows, policies, and other relevant settings) from the dev environment and apply it to the other environments. Ideally, we are looking for a way to streamline this process to ensure consistency across all environments while minimizing manual intervention.

Could you confirm if this is feasible with KC-CLI and provide any guidance or examples on how to approach it?

Thank you!

**Comment by Motouom** [comment]
@Adderin  While kccli lacks a dedicated mechanism for exporting the state of Keycloak realms and properties, you can leverage the `Keycloak API through a shell script` to export the desired configuration. After exporting the realm state, particularly with the configured MFA, you can refine the output to extract the relevant UID, since kccli identifies properties using usernames. This approach is documented in ticket  #933, where a workaround utilizing `jq` for ID filtering was suggested.

Once you have a clean configuration, you can utilize the `--import.files.locations=<path>` option in the shell script to apply these configurations to your environment. Additionally, consider exploring other configurable CLI properties for synchronization, such as `--import.remote-state.enabled=<value>` and `--import.parallel=<value>`. All these processes can be scripted to create a robust solution for managing Keycloak configurations across your environment
