### ISSUE TITLE
config generation from export

### ISSUE THREAD

**Issue by viyullas** [adorsys/keycloak-config-cli#288]
**It would be nice to have some kind of utility or set of instructions to adapt an export.json file to a configuration file valid for 
keycloak-config-cli**
Right now I am in the process of automating the deploymet and maintenace via CICD of an already working keycloak server and this utility seems the best way to track all the changes and keep the database of every new environment we start up to date with the production servers. My problem is that I am not a programmer so I am not very used to work with json and our export is quite big, son I am a little bit overwelmed with the task of making changes to it to adapt it to be used with keycloak-config-cli.

**Describe the solution you'd like**
Some kind of parser that strips out all the things not needed from the export.

**Describe alternatives you've considered**
A set of instructions to do it manually

**Comment by jkroepke** [comment]
hm, the problem is, Keycloak doesn't provide any default. It's unknown to `keycloak-config-cli` what has been changed, what not.

> A set of instructions to do it manually

I have an idea here.

* Get an full export of your realm
* Setup an empty instance keycloak instance
* Create a realm using the name like the production realm, then do an export.
  * Keycloak provides a partial export via web UI, otherwise
  * https://www.keycloak.org/docs/latest/server_admin/index.html#_export_import
* Start compare both json files and remove keys with same values.
* Start an new empty keycloak instance
* import the new realm json
* do an export again and compare the export with original export

Additionally `keycloak-config-cli` supports YAML format. It might be more readable then JSON files. You could also convert the json files to YAML before comparing them.
