### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by daniel-shuy** [adorsys/keycloak-config-cli#295]
Thanks for this tool! It would be even better if there is a JSON Schema for the JSON configuration file!

Edit: Just found out from https://keycloak.discourse.group/t/keycloak-configuration-cli-configuration-as-code-for-keycloak/1703 that the schema is the same as the `realm-export.json` schema. Anyone knows if there is a JSON Schema for it?

**Comment by jkroepke** [comment]
Hi @daniel-shuy 

correct, this tools doesn't define a new JSON Syntax, it just aims to be compatible to be 100% compatible with the keycloak realm schema.

All properties are defined here: https://www.keycloak.org/docs-api/11.0/rest-api/index.html#_realmrepresentation

Based on that, this question or feature request is better at https://issues.redhat.com/ or https://keycloak.discourse.group/


What I found:

- https://issues.redhat.com/browse/KEYCLOAK-14321
- https://groups.google.com/g/keycloak-dev/c/j1ZbooAHqsw/m/TnZey8cIDAAJ
- https://github.com/ccouzens/keycloak-openapi/

Since the last project do some auto generated based on the keycloak code, you could the quest there, too.

https://github.com/ccouzens/keycloak-openapi/blob/d75b656fef9be0af677af54dd23efa57de6b4b7b/keycloak/12.0.json#L12509
