### ISSUE TITLE
Executing import but not saving changes eg. dry-run, or diff

### ISSUE THREAD

**Issue by todeb** [adorsys/keycloak-config-cli#313]
Hi, 

it might be usefull in some cases to just check and have an overview what will be changed, before running the actual import.

**Comment by jkroepke** [comment]
A dry-run might not possible, I had to much to mock all the requests.

But I could think about a diff feature. I guess that would be helpful.

**Comment by jkroepke** [comment]
Hi!

I tried some inside the [wip-diff](https://github.com/adorsys/keycloak-config-cli/tree/diff-wip) branch. But I could not find a java library that handle the yaml diff on stdout well.

I guess, I could not implement that.

**Comment by valb3r** [comment]
@jkroepke I think it can be done via Json diff and alike. See
https://github.com/valb3r/yaml-diff-example/blob/master/src/test/java/YamlDiff.java
Javers lib can be configured to produce cleaner output, and JsonDiff output can be prettified as well

**Comment by jkroepke** [comment]
I played around with https://github.com/google/diff-match-patch to create diff from yaml. But I'm not able to generate useful diffs, since most of the local configuration does not include ids + there is no way to get a full dump of a realm.

Masking secrets from the output is a new different topic. I'm going to close this, since its not really possible yet.

The best possible approach would be to store the whole the while configuration in the keycloak database, but then the import diff would be only based on the latest keycloak config cli run. That could confuse a lot of poeple.
