### ISSUE TITLE
keycloak-config-cli as Maven/Ivy dependency

### ISSUE THREAD

**Issue by mknittig** [adorsys/keycloak-config-cli#373]
**Is your feature request related to a problem? Please describe.**

I would like to use keycloak-config-cli as a Gradle depdendency.

**Describe the solution you'd like**

Update the JARs in the central repository (there are outdated currently).

**Describe alternatives you've considered**

Point me to another public repository which has the current version of keycloak-config-cli.

**Comment by jkroepke** [comment]
Hi,

it's not planned to publish keycloak-config-cli to a public repository. I think it's the wrong place.

From what I understand maven central is a good spot for libraries/frameworks but keycloak-config-cli would not fit into this, since it act an end user binary.

There are some zero versions of keycloak-config-cli but it's not possible to delete the version. There are deprecated leftovers.

> I would like to use keycloak-config-cli as a Gradle depdendency.

Maybe you could archive this by using a [source dependency](https://blog.gradle.org/introducing-source-dependencies).

**Comment by mknittig** [comment]
OK, thanks. I understand that this is a bit of a edge user case but we want to use it programatically to create new realms. I'll take a look at source dependency.
