### ISSUE TITLE
Delete clients not present in import file

### ISSUE THREAD

**Issue by qrider71** [adorsys/keycloak-config-cli#398]
When importing the JSON with the CLI we noticed that clients already present in keycloak but missing in the imported json file did not get deleted. We deleted a client manually in Keycloak but missed out deleting a role mapper with references to the deleted client. This caused a crash of our keycloak instance.

Feature Request: The CLI should delete and clean-up items and referenced items present in keycloak but not present in the json import file

**Comment by jkroepke** [comment]
Hi @qrider71 

since [v3.0.0](https://github.com/adorsys/keycloak-config-cli/blob/v3.0.0/CHANGELOG.md) the keyconfig-config-cli will only delete clients that are created by keycloak-config-cli itself.

Thats prevent fatal situations. Some clients are "system relevant" and should not be deleted (like the account client), but such builtin clients are not marked as builtin.

You could disable this behavior by setting `--import.state` to `false`. 

Then keycloak-clonfig-cli still tries to detect default clients https://github.com/adorsys/keycloak-config-cli/blob/29c62f79342334116c5fabf5858741129092288c/src/main/java/de/adorsys/keycloak/config/util/KeycloakUtil.java#L33-L46 but this isn't guarantee in future Keycloak versions.

Let me know, if this helps.
