### ISSUE TITLE
Please document the `--debug` and `--trace` command line options and the `KEYCLOAK_LOGLEVEL`  and `ROOT_LOGLEVEL` envs

### ISSUE THREAD

**Issue by pmorch** [adorsys/keycloak-config-cli#431]
**Is your feature request related to a problem? Please describe.**

It would be nice to have documented how to increase log level when things go south. I've forgotten how I noticed the  `--debug` and `--trace` command line options, but today I find mention of  `KEYCLOAK_LOGLEVEL`  and `ROOT_LOGLEVEL` environment variables in `src/test/java/de/adorsys/keycloak/config/AbstractImportTest.java`.

**Describe the solution you'd like**
I'd like the options and environment variables documented in `README.md`.

I can sort of guess how they all work, but I couldn't find the code that reads the options and environment variables. (How can the strings `getenv` and `LOGLEVEL` not be found in `src/main` but envs still work somehow?) Because of that I'm not able to create a PR for this myself. Especially, is `--debug` the equivalent of `KEYCLOAK_LOGLEVEL="DEBUG"` or does it set `ROOT_LOGLEVEL="DEBUG"` too? Do the envs provide more control or are there more options I haven't found yet?

Perhaps mention how to increase logging in these github issue templates too, if you'd like more verbose info in issues.

**Comment by jkroepke** [comment]
Hi @pmorch 

`KEYCLOAK_LOGLEVEL` and `ROOT_LOGLEVEL` are used inside the integration tests to configure the Keycloak. The environment variables are supported from the docker container of Keycloak and do nothing at keycloak-config-cli. (except there is some hidden magic)

Currently, keycloak-config-cli does not implement logging. Since keycloak-config-cli using spring boot, the spring boot logging is used here. At the point, the README.md covers options implement by keycloak-config-cli itself.

> I'd like the options and environment variables documented in README.md.

The spring boot logging implements a lot of functions (some unknown to me), the documentation around logging may be huge.

Some upstream documentation:

* https://docs.spring.io/spring-boot/docs/2.5.0/reference/html/features.html#features.logging.console-output
* https://docs.spring.io/spring-boot/docs/2.5.0/reference/html/features.html#features.logging.log-levels

I don't know, how `--debug` and `--trace` are useful, because it will be log everything coming from spring boot internals, too.
Reading the docs, I would except that `--debug` is `DEBUG=true` on environment side.

The root log level can be defined by env var `LOGGING_LEVEL_ROOT`. `LOGGING_LEVEL_DE_ADORSYS` reference classes from keycloak-config-cli.

`LOGGING_LEVEL_ORG_APACHE_HTTP_WIRE=debug` dumps the http requests and responses between keycloak-config-cli and Keycloak.

There are 2 spring profiles like [debug](https://github.com/adorsys/keycloak-config-cli/blob/main/src/main/resources/application-debug.properties) and [http-debug](https://github.com/adorsys/keycloak-config-cli/blob/main/src/main/resources/application-http-debug.properties) and be enabled via `--spring.profiles.active=debug` or `SPRING_PROFILES_ACTIVE=debug`. (may change in future).

Does it help? If yes. I could write something about the profile in the README.md.

**Comment by pmorch** [comment]
Ok, i might have misunderstood their usefulness. If you think they don't provide help when things aren't working, then phase just close this.

Things are working fine for me now, so i don't have a problem that needs debugging. I just saw "more logging" with e.g --debug and assumed it would help. Perhaps not.

Sorry to waste you time twice in one day...
