### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by Cyben** [adorsys/keycloak-config-cli#506]
Hey,
I'm really interested in this project, and I would like to use it.
But before that I have a few questions.

1. I can see that in the latest version of this project there is no support for old versions of Keycloak,
I would like to know why, as far as I know there is no difference in the api.

2. How do you manage clients with this project?
In my case I can have up to 5 thousand of clients, and I don't see myself managing them all from this configuration file, and as you mentioned in the README.md, it is recommended to keep the configuration file small.

**Comment by jkroepke** [comment]
> I would like to know why, as far as I know there is no difference in the api.

Older versions of keycloak contains some bugs. By dropping older versions, I can remove some workarounds inside the code to keep it clean.

The execution time in github action is limited, I would not like able to run tests for 8 different Keycloak versions. Since it consume a lot of minutes. I would not like to support a version, if I'm not running tests for that version.

Until keycloak-config-cli 3 I tried to support much versions as possible, it was a little painful.

But, I'm not deleting the test executions. If you have an old keycloak version, you can run tests locally to verifiy if keycloak-config-cli works on an unsupported version.

> How do you manage clients with this project?
Up to 5 thousand, in such a case I would recommend to have an additional generator (based on templates) that generated the yaml files. 

I don't know if keycloak-config-cli can handle such large amount of resources, it's still java.

> it is recommended to keep the configuration file small.
Thats correct. The focus of the message is not including default values or uuids. But in this case, if you have 5000 client, there is no other chance except group them in multiple files.


In case keycloak-config-cli wont fit here, you could take a look at 
https://github.com/mrparkers/terraform-provider-keycloak

**Comment by Cyben** [comment]
Awesome, thank you very much!
