### ISSUE TITLE
Client Authorization Resources get deleted

### ISSUE THREAD

**Issue by borislav72** [adorsys/keycloak-config-cli#511]
Hello,

We stared using keycloak-config-cli, but we have a problem with the following case: 
1. A client is created via keycloak-config-cli. 
2. Authorization resource is created for that client using Keycloak API and users are granted permissions to that resource. 
3. When keycloak-config-cli is run again, the authorization resource gets deleted.

In  ClientImportService.java I see:

`
 ​private static final String[] propertiesWithDependencies = new String[]{
           ​"authenticationFlowBindingOverrides",
           ​"authorizationSettings",
   ​};
`
...............................................
`   
       ​String[] propertiesToIgnore = ArrayUtil.concat(propertiesWithDependencies, "id", "access");
       ​ClientRepresentation mergedClient = CloneUtil.patch(existingClient, clientToUpdate, propertiesToIgnore);
`

Is there a reason to ignore ​"authorizationSettings" property when client is merged?
Is there a way to keep exiting authorization resources in the scenario above?

Thank you!

**Comment by jkroepke** [comment]
HI @borislav72 

in general, its expected that changes outside keycloak-config-cli are removed. 

`authorizationSettings` are ignored on first, since they depend on other resources like groups or roles.

The clients `authorizationSettings` just handled at a later stage

https://github.com/adorsys/keycloak-config-cli/blob/a82f8b9d5335c54bc7e68b1ff38e1570991dea63/src/main/java/de/adorsys/keycloak/config/service/ClientImportService.java#L255

Thats the reason, why the `authorizationSettings` getting removed. If keycloak-config-cli could not find any `authorizationSettings`, they will be removed. 

https://github.com/adorsys/keycloak-config-cli/blob/a82f8b9d5335c54bc7e68b1ff38e1570991dea63/src/main/java/de/adorsys/keycloak/config/service/ClientImportService.java#L290-L303

> Is there a way to keep exiting authorization resources in the scenario above?

1. Instead configure the `authorizationSettings` outside of keycloak-config-cli, put them inside your import file.
2. Inside your import file, remove the key `authorizationSettings`. If `authorizationSettings` is not defined, the `authorizationSettings` for that specific client will be ignored.
  
  https://github.com/adorsys/keycloak-config-cli/blob/a82f8b9d5335c54bc7e68b1ff38e1570991dea63/src/main/java/de/adorsys/keycloak/config/service/ClientImportService.java#L261-L263

**Comment by borislav72** [comment]
@jkroepke Thank you for the explanation. Option 2) works for us.
