### ISSUE TITLE
RFC: Officially dropping java 8 and 11 support

### ISSUE THREAD

**Issue by jkroepke** [adorsys/keycloak-config-cli#622]
Some dependencies like [SpringBoot](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Release-Notes#minimum-requirements-changes) going to introduce new major versions which requires at least Java 17.

This may have an impact of keycloak-config-cli in the future and I'm thinking about to drop Java 8 and Java 11 support here.

On good side, keycloak-config-cli does not have any call to home functions and I have no idea how many users are compile  keycloak-config-cli itself and use java 8 or java 11. 

By default, the container image and the prebuilt jars using currently java 17 while the language level is still 1.8.

I'm requesting for comments here to gain an understanding in which places keycloak-config-cli i used. If you are still rely on java < 17, please give a context why you need to stay on java 8 or java 11.

**Comment by ianwallen** [comment]
We are currently a java 11 shop mostly due to the LTS support

https://endoflife.date/java

17 is still fairly new and we will be waiting a little bit for it to mature before we switch over.  Hopefully we can start the upgrade process in the next couple month but it will depend on our upper management priorities.

8 is coming to the end of it basic support so no objection from me in dropping support.

**Comment by jkroepke** [comment]
I will remove java 8 support soon See: #677
