### ISSUE TITLE
Changing a username while keeping the email unchanged leads to 409 conflict

### ISSUE THREAD

**Issue by tobilarscheid** [adorsys/keycloak-config-cli#662]
### Current Behavior

1. Create a realm.yaml that contains a user with a name and an email address
2. Run `keycloak-config-cli` to apply the realm.yaml
3. Change the realm.yaml so that the user's email stays the same but the username is changed
4. Rerun `keycloak-config-cli` --> error, 409 Conflict

### Expected Behavior

A new user with the new name should be created, the old user should disappear

### Environment

- Keycloak Version: 16.0.1
- keycloak-config-cli Version: latest
- Java Version: 11

**Comment by jkroepke** [comment]
Deleting users is currently not implemented in keycloak-config-cli, only create and update.

Thats why keycloak-config-cli will not delete the old user and the new user has a conflict with the existing user.

**Comment by testuser7** [comment]
Is there any plan to add the remote state feature?

**Comment by tobilarscheid** [comment]
Hi @testuser7 (what a name ;-) ), I haven't looked into it so far!

**Comment by AssahBismarkabah** [comment]
Hi @testuser7 

this also closes ticket https://github.com/adorsys/keycloak-config-cli/issues/810 since the username needs to be uniquely identified, 
also setting the `--import-remote-state.enable="true"` should also be given a trial to see if the issue persist.

**Comment by Calebasah** [comment]
After testing, I observed that Keycloak uses the `username` as the unique identifier for users. This causes the following behavior:

- Changing only the `username` during an import results in a `409 Conflict`.
- Changing the `username` along with other attributes creates a `new user` without deleting the old one because purging users isn’t supported 
 by keycloak-config-cli.

Recommendation:
- Consider enabling `Edit Username` in the realm settings.
- Explore alternative identifiers like `email` for user matching during imports.

**Comment by Motouom** [comment]
This ticket is similar to ticket #810. 

Reference to it for more information
