### ISSUE TITLE
Re-add information lost in recent formatting update of the README

### ISSUE THREAD

**Issue by jack1902** [adorsys/keycloak-config-cli#714]
### Problem Statement

previous iterations of the README.md had a snippet about `--import.force` but this is no longer present, I can see it got dropped in this commit: https://github.com/adorsys/keycloak-config-cli/commit/c1f8a97eb272cae608339fad8dec0a09dea7bc85 and this PR: https://github.com/adorsys/keycloak-config-cli/pull/677

### Proposed Solution

Re-add information around `--import.force` (i believe it is still a thing but from the docs it is unclear what it is)

### Environment

- Keycloak Version: [e.g. 10.0.1]
- keycloak-config-cli Version: [e.g. 1.4.0]
- Java Version: [e.g. 11]

### Acceptance Criteria

- [ ] As a CLI user, previously documented flags are re-documented

**Comment by st3v0rr** [comment]
Hi @jack1902 ,
as you already mentioned we removed the property with the latest releases since v5.0.0
If you are using an older version the docs are still reachable in the v4.9.0 tag.

https://github.com/adorsys/keycloak-config-cli/tree/v4.9.0

Due to an easier maintenance of this project we try to avoid keeping no longer available features in the main branch.

**Comment by jack1902** [comment]
Ah ok, apologies, I thought it was still an option within the project. I'm assuming `force` happens now regardless?

**Comment by st3v0rr** [comment]
The new property is import.cache.enabled.
If you set it to false (is true by default) the behavior should be the same as in v4.9.0 and earlier.
