### ISSUE TITLE
How to use import file content with json array into realm config

### ISSUE THREAD

**Issue by KWierchomska** [adorsys/keycloak-config-cli#838]
Hi, I want to import protocolMappers, which are defined in separate file into realm config file.
My file protocolMappers.json looks something like this 
`[
  {
    "name": "xyz",
    "protocol": "openid-connect",
    "protocolMapper": "oidc-usermodel-attribute-mapper",
    "consentRequired": false,
    "config": {
      "userinfo.token.claim": "true",
      "multivalued": "false",
      "user.attribute": "xyz",
      "id.token.claim": "true",
      "access.token.claim": "true",
      "claim.name": "xyz",
      "jsonType.label": "int"
    }
  }
]`

and when I want to import it into realm config using       
`"protocolMappers": "$(file:UTF-8:properties/protocolMappers.json)"`
 if gives me something like this 
 
 `"protocolMappers": "[
  {
    "name": "xyz",
    "protocol": "openid-connect",
    "protocolMapper": "oidc-usermodel-attribute-mapper",
    "consentRequired": false,
    "config": {
      "userinfo.token.claim": "true",
      "multivalued": "false",
      "user.attribute": "xyz",
      "id.token.claim": "true",
      "access.token.claim": "true",
      "claim.name": "xyz",
      "jsonType.label": "int"
    }
  }
]"
`

so the array is inserted as a String and config can not be properly parsed, how can I resolve this issue?

**Comment by Motouom** [comment]
Hello @KWierchomska,

Thank you for reporting the issue.

In this case, you cannot directly include the contents of another file in a JSON file. JSON does not support file inclusion or templating natively. It is a data interchange format designed for representing structured data and lacks built-in mechanisms for including external files or templating. 

However, there are several third-party solutions and extensions that offer file inclusion or templating capabilities for JSON:

- **JSON-include**: An extension that allows for file inclusion in JSON using a special syntax.
- **json-templates**: An NPM package that facilitates simple JSON value templating.
But using these third party methods might or will not be beneficial since it's too much stress which does not still solve the problem concretely.
