### ISSUE TITLE
Realm Import of file that has groups with IDs fail with 404

### ISSUE THREAD

**Issue by zts3y** [adorsys/keycloak-config-cli#877]
### Current Behavior

When importing an exported realm file that includes group `id`, keycloak-config-cli returns `Create method returned status Not Found (Code: 404); expected status: Created (201)`. 

This was mentioned in #824 as well, and the user mentioned a workaround in the code. 

### Expected Behavior

An exported realm file from a supported keycloak installation should be able to import fully.

### Steps To Reproduce

```markdown
1. Export a realm as JSON with all groups and roles
2. Using keycloak-config-cli, point to the freshly exported realm.json file
```

### Environment

- Keycloak Version: 21.1.1
- keycloak-config-cli Version: 5.6.1
- Java Version: 17

**Comment by Motouom** [comment]
Hello @zts3y, you can refer to this [ticket](https://github.com/adorsys/keycloak-config-cli/issues/824) for information concerning your issue

If you need more ideas on how to do go around you issue, here are some proposed solutions that you can try:

Since importing groups containing IDs is a limitation of Keycloak's API itself, rather than a problem specific to keycloak-config-cli. However, we can provide a concrete example and a workaround for others facing this issue. Here's a suggested approach that might be interesting:

## Example of the issue:
- You create a json file  with groups containing ids.
- When trying to import this configuration using keycloak-config-cli, you'll encounter the ```"Create method returned status Not Found (Code: 404)" error.```

# Workaround:
To work around this issue, you can follow these steps:

## a. Remove the "id" field from your import file for groups:

## b. Import this modified configuration using keycloak-config-cli.

## c. After import, if you need to interact with the groups using their IDs, you can use the Keycloak API to retrieve the group IDs. Here's an example using curl:
```bash


# Function to display a message for obtaining the access token
get_access_token() {
  echo "Requesting access token..."
  TOKEN=$(curl -s -X POST "http://localhost:8080/realms/master/protocol/openid-connect/token" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "grant_type=password" \
    -d "client_id=admin-cli" \
    -d "username=admin" \
    -d "password=admin" | jq -r '.access_token')

  if [ -z "$TOKEN" ]; then
    echo "❌ Failed to obtain access token. Please check your credentials and Keycloak URL."
    exit 1
  else
    echo "✅ Access token obtained successfully."
  fi
}

# Function to retrieve groups and display only name and ID
#the moped in the url and the code is the name of my realm, you can replace it with yours
retrieve_groups() {
  echo "Retrieving groups from the 'moped' realm..."
  GROUPS=$(curl -s -X GET "http://localhost:8080/admin/realms/moped/groups" \
    -H "Authorization: Bearer $TOKEN")

  if echo "$GROUPS" | jq . >/dev/null 2>&1; then
    echo "✅ Groups retrieved successfully."
    echo "Group Name and ID in the 'moped' realm:"
    echo "$GROUPS" | jq -r '.[] | "\(.name): \(.id)"'
  else
    echo "❌ Failed to retrieve groups. Please check your Keycloak URL and realm name."
    echo "Response: $GROUPS"
    exit 1
  fi
}

# Main Script Execution
get_access_token
retrieve_groups

```
## Recommendation for automation:
If you're using this in an automated process (like with Ansible), you could import the script into your ansible file as such
```yaml
  tasks:
    - name: Run group retrieval script
      shell: /path/to/your-script.sh
      <--add the other sections of the code-->
```
